### ISSUE TITLE
Migration guide from ipfs-http-client to helia

### ISSUE THREAD

**Issue by VladimirMikulic** [ipfs/helia#153]
Hi! Could you please provide migration guide from ipfs-http-client to helia?
(e.g. add, addAll, urlSource, globSource etc.)

https://www.npmjs.com/package/ipfs-http-client

**Comment by lukachi** [comment]
any updates here?
I have same question.
i've deployed ipfs node on own private network and use ipfs-http-client url with ipfs gateway,
so what use cases should be done for store and get files, strings or json? with directory or just by address.

**Comment by VladimirMikulic** [comment]
@whizzzkid I appreciate the reply here, but I'm still not sure how we'd do this migration.
How would this example snippet look like with Helia?

```js
import { create, urlSource } from 'ipfs-http-client';
const client = create({
  host: 'ipfs.infura.io',
  port: 5001,
  protocol: 'https',
  headers: {
    authorization: "Infura auth string"
  }
});

const file = await client.add(urlSource("https://domain/image.jpeg"));
```

**Comment by VladimirMikulic** [comment]
Great! Thank you for your help @whizzzkid!
