### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by oed** [ipfs/helia#655]
- https://ipfs.github.io/helia redirects to https://helia.io
- **API** on helia.io redirects back to the same page

**Comment by 2color** [comment]
This should be fixed now. Can you try again to confirm?

**Comment by SgtPooki** [comment]
@oed I ran into this issue with Brave browser.. The API link was redirecting me from [ipfs.github.io/helia](http://ipfs.github.io/helia) to [helia.io](http://helia.io/), and was only stopped when I toggled off the ‘auto-redirect tracking urls’ in brave

![image](https://github.com/user-attachments/assets/38809197-1265-4a9d-a58a-87ebc34918e2)

it may be similar in others? try an incognito tab or different browser to see that it is all set up properly.

**Comment by oed** [comment]
I'm still seeing the issue in Firefox, but yes if I open an incognito tab [ipfs.github.io/helia](http://ipfs.github.io/helia) works 🤔

**Comment by SgtPooki** [comment]
Try disabling then enabling firefox tracking protections in firefox (via extensions or other..) and hopefully that will resolve the issue?

**Comment by oed** [comment]
I'd rather not disable tracking protections

**Comment by 2color** [comment]
https://github.com/ipfs/helia/pull/666 should fix this. Turns out removing the custom domain manually only worked until another commit to main came in.
